### ISSUE TITLE
data question

### ISSUE THREAD

**Issue by yyyyyuzj** [bioinfodlsu/phage-host-prediction#2]
![image](https://github.com/bioinfodlsu/phage-host-prediction/assets/121244675/6f241a8f-f03d-44ae-ad67-05084ba08835)
![image](https://github.com/bioinfodlsu/phage-host-prediction/assets/121244675/c82dbd1c-8e58-43a0-a83a-93a53463e1cc)
I downloaded this compressed file, but there is no rbp folder in this folder

**Comment by memgonzales** [comment]
Hello! You can download the `rbp` folder using this link:
**https://drive.google.com/drive/folders/1mCjdkJZVbueNHv-7p0h9pxPM9nGtDe9A?usp=drive_link**

<br>

![image](https://github.com/bioinfodlsu/phage-host-prediction/assets/44253974/0f3962f6-f0fa-4e00-99ca-22cb53eaa5a3)

Only `prottransbert` has an `rbp` folder. 

If something is unclear or if you have some more questions, feel free to let me know.

**Comment by memgonzales** [comment]
Hello! I will be closing this issue, as there has not been any activity for the past month. 

Feel free to open it again should you have some more questions. Thanks!
